name:                mult3plus1
version:             0.1.0.0
github:              "nqpz/mult3plus1"
license:             WTFPL
author:              "Niels G. W. Serup"
maintainer:          "ngws@metanohi.name"
copyright:           "Copyright (c) 2019 Niels G. W. Serup"

extra-source-files:
- README.md

synopsis:            An attempt at solving the Collatz conjecture

description:         Please see the README on GitHub at <https://github.com/nqpz/mult3plus1#readme>

dependencies:
- base >= 4.7 && < 5
- fgl >= 5.8
- graphviz >= 2999.20
- text >= 2.0

library:
  source-dirs: src

executables:
  mult3plus1-modulo:
    main:                modulo.hs
    source-dirs:         src
    dependencies:
    - mult3plus1
  mult3plus1-symbolic:
    main:                symbolic.hs
    source-dirs:         src
    dependencies:
    - mult3plus1
